# Generated by Django 2.1.5 on 2019-02-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190201_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Financial'), (1, 'Non Financial')], default=0),
        ),
    ]
